apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dhcp-service
spec:
  template:
    spec:
      containers:
        - image: docker.io/manishjha8909/dhcp-serverless:latest # Explicit registry
          env:
            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local"
          ports:
            - containerPort: 8080
          # REMOVE imagePullPolicy - Knative ignores this field!
          securityContext: # Recommended for production
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
      # REMOVE imagePullSecrets if your Docker Hub repo is public
