apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dhcp-service
spec:
  template:
    spec:
      containers:
        - image: dhcp-serverless:latest
          env:
            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local" 
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
      imagePullSecrets:
        - name: your-registry-cred
