apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dhcp-service
spec:
  template:
    spec:
      containers:
        - image: your-registry/dhcp-serverless
          env:
            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local"