apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dhcp-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        dhcp/update-time: "{{REPLACE_WITH_TIMESTAMP}}" # Patch this manually when needed
    spec:
      containers:
        - image: docker.io/manishjha8909/dhcp-serverless:latest
          env:
            - name: REDIS_ADDR
              value: "redis-master.redis.svc.cluster.local:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis # Secret must be in 'default' namespace
                  key: redis-password
            - name: IP_POOL_START
              value: "192.168.1.100"
            - name: IP_POOL_END
              value: "192.168.1.200"
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
