FROM golang:1.19 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the client binary
RUN go build -o bin/client client.go

# Lightweight runtime image
FROM debian:bullseye-slim

# Copy binaries from the builder
COPY --from=builder /app/bin/client /app/bin/client

# Entry point for the client
ENTRYPOINT ["/app/bin/client"]

CMD []
